[package]
name = "monitoring"
version = "0.1.0"
authors = ["Josh Mcguigan"]
edition = "2018"

[dependencies]
trust-dns-client = "0.18.0-alpha.3"
hubcaps = "0.5.0"
tokio = "0.1.0"
futures = "0.1"
dotenv = "0.11.0"
